apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: ydp3yauiy-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0a402eecd9.0jv5.p3.openshiftapps.com/rhtap/rhtap-qe:bb4385378bd95fe2677c87f0beb082c2bf9b194f@sha256:f83a3386e4156556fa507e23a9c464e636cced7ebf3bbfae16d5e6037a071c66
        name: container-image  
